name: repostats
description: Collects various repository statistics.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

dependencies:
  args: ^2.5.0

environment:
  sdk: ">=2.12.0 <3.0.0"
